### ISSUE TITLE
'save' command is counterintuitive

### ISSUE THREAD

**Issue by dfosco** [hyperspace/hyperspace#16]
Had to watch the youtube tutorial to figure out the `hyperspace save` command _starts_ a new project.

The README doesn't give it too much emphasis either:

![image](https://cloud.githubusercontent.com/assets/3229933/26064107/5dbca846-3966-11e7-8222-d4653130448c.png)

I'd say at least indicate in the README that the save command starts a project, but a `hyperspace start` or `hyperspace new`would be ideal

**Comment by zehfernandes** [comment]
Implement `new` command in v1.0.6 👍
