### ISSUE TITLE
You need allow accessibility access

### ISSUE THREAD

**Issue by podrivo** [hyperspace/hyperspace#20]
Não consegui salvar um projeto, sendo que já habilitei o "accessibility access" no sistema.
Já reinstalei o Phoenix também. To no Sierra 10.12.5.
```
➜  ~ hyperspace save

? Save your current open files and apps + Create new project
? 🌟  Type the project name teste
? ✏️  Type the project description (be poetic) testando
Setup phoenix lib

Open Phoenix.app

Start snapshot process...
Get all windows
Change to space 1 from display 1

You need allow accessibility access
Go to System Preferences > Security & Privacy > Privacy > Accessibility
And check your terminal app and the Phoenix.app
```
![captura de tela 2017-06-06 as 00 40 46](https://cloud.githubusercontent.com/assets/546221/26812877/d660b65c-4a50-11e7-8f94-052b1c324a71.png)

**Comment by zehfernandes** [comment]
Subi um fix para suporte do OS em vários idiomas ac1ff4a5b98091bd74c86d10ef49972e651501ee

Instala a ultima versão e tenta novamente.

```
npm install -g hyperspace-cli@1.0.7
```

**Comment by podrivo** [comment]
Deu certo! (:
Ques alterações bizarras pra ser algo relacionado à idioma, haha.

E mano, acho que faltou um `to` em `You need TO allow accessibility access`.
